<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Views\Employee\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Employee\Delete.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Employee\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Employee\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Employee\Index.cshtml" />
    </ItemGroup>

</Project>
