// <auto-generated />
using System;
using Lab0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251124173035_AddOrganizationRelation")]
    partial class AddOrganizationRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Lab0.Models.AlbumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChartPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Songs")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Band = "Linkin Park",
                            ChartPosition = 2,
                            Name = "Hybrid Theory",
                            ReleaseDate = new DateOnly(2000, 10, 24),
                            Songs = "In the End;Crawling",
                            TotalDuration = new TimeSpan(0, 0, 37, 45, 0)
                        },
                        new
                        {
                            Id = 2,
                            Band = "Nirvana",
                            ChartPosition = 1,
                            Name = "Nevermind",
                            ReleaseDate = new DateOnly(1991, 9, 24),
                            Songs = "Smells Like Teen Spirit;Come As You Are",
                            TotalDuration = new TimeSpan(0, 0, 49, 23, 0)
                        });
                });

            modelBuilder.Entity("Lab0.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adam@wsei.edu.pl",
                            Name = "Adam"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ewa@wsei.edu.pl",
                            Name = "Ewa"
                        },
                        new
                        {
                            Id = 3,
                            Email = "karol@op.pl",
                            Name = "Karol"
                        });
                });

            modelBuilder.Entity("Lab0.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Organization");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Address = "Św. Filipa 17, Kraków",
                            Name = "WSEI"
                        },
                        new
                        {
                            Id = 102,
                            Address = "Polska",
                            Name = "PKP"
                        });
                });

            modelBuilder.Entity("Lab0.Models.Contact", b =>
                {
                    b.HasOne("Lab0.Models.Organization", "Organization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Lab0.Models.Organization", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
